name: duckit_labs_bebe_app_workspace
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

workspace:
  - apps/bebe_app
  - packages/app_base

dev_dependencies:
  melos: ^8.0.0

melos:
  scripts:
    bs:
      description: Bootstrap workspace.
      run: melos bootstrap

    list:
      description: List packages.
      run: melos list

    analyze:
      description: Analyze packages.
      run: melos exec -- dart analyze .

    run:app:
      description: Run BebéApp.
      run: melos exec --scope=bebe_app -- flutter run

    run:app:android:
      description: Run BebéApp Android.
      run: melos exec --scope=bebe_app -- flutter run -d android

    run:app:ios:
      description: Run BebéApp iOS.
      run: melos exec --scope=bebe_app -- flutter run -d ios