name: duckit_labs_bebe_app_workspace
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

workspace:
  - apps/bebe_app
  - packages/notifications
  - apps/widgetbook
  - packages/app_base
  - packages/app_layout
  - packages/auth
  - packages/core
  - packages/design_system
  - packages/home
  - packages/agenda
  - packages/health
  - packages/register
  - packages/family
  - packages/login
  - packages/onboarding
  - packages/splash
  - packages/signup

dev_dependencies:
  melos: ^8.2.0

melos:
  scripts:

    build_runner:
      description: Generate source code in selected packages.
      exec:
        command: dart run build_runner build --delete-conflicting-outputs
        concurrency: 1
        failFast: true
      packageFilters:
        dependsOn:
          - build_runner

    analyze:
      description: Analyze packages.
      run: melos exec -- dart analyze .

    run:app:
      description: Run BebéApp.
      run: melos exec --scope=bebe_app -- flutter run --flavor development --dart-define-from-file=config/development.env.json

    run:app:android:
      description: Run BebéApp Android.
      run: melos exec --scope=bebe_app -- flutter run -d android --flavor development --dart-define-from-file=config/development.env.json

    run:app:ios:
      description: Run BebéApp iOS.
      run: melos exec --scope=bebe_app -- flutter run -d ios --flavor development --dart-define-from-file=config/development.env.json
