name: login
description: Experiencia de inicio y recuperación de sesión de BebéApp.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.22.0"

resolution: workspace

dependencies:
  auth:
  design_system:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1

dev_dependencies:
  bloc_test: ^10.0.0
  core:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_lints: ^6.0.0
