flutter_native_splash:
  color: "#FAFAFC"
  image: assets/branding/native_splash/splash_symbol_light.png

  color_dark: "#0F2A2D"
  image_dark: assets/branding/native_splash/splash_symbol_dark.png

  android: true
  ios: true
  web: false
  fullscreen: false

  android_12:
    color: "#FAFAFC"
    image: assets/branding/native_splash/splash_symbol_light.png
    icon_background_color: "#FAFAFC"

    color_dark: "#0F2A2D"
    image_dark: assets/branding/native_splash/splash_symbol_dark.png
    icon_background_color_dark: "#0F2A2D"
