flutter_launcher_icons:
  android: true
  ios: true

  image_path: assets/branding/launcher/bebeapp_launcher_night_1024.png
  image_path_android: assets/branding/launcher/bebeapp_launcher_night_1024.png
  image_path_ios: assets/branding/launcher/bebeapp_launcher_night_1024.png
  remove_alpha_ios: true
  background_color_ios: "#003F46"

  adaptive_icon_background: assets/branding/launcher/bebeapp_launcher_background_1024.png
  adaptive_icon_foreground: assets/branding/launcher/bebeapp_launcher_foreground_1024.png
  adaptive_icon_monochrome: assets/branding/launcher/bebeapp_launcher_monochrome_1024.png
  adaptive_icon_foreground_inset: 12
