name: splash
description: Flujo de entrada, autenticación inicial y splash Flutter de BebéApp.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  core:
  design_system:
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  go_router: ^16.3.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.7.0
  freezed: ^3.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/branding/light/
    - assets/branding/dark/
