name: widgetbook_app
description: DuckIT BebéApp widget catalog.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

platforms:
  android:
  ios:
  web:
  windows:

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../packages/core
  design_system:
    path: ../../packages/design_system
  app_layout:
    path: ../../packages/app_layout

  widgetbook: ^3.25.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0